# Generated by Django 3.1.3 on 2020-11-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=4)),
                ('team_points', models.IntegerField(default=1000)),
                ('points_float', models.FloatField(default=1000)),
                ('sigma', models.FloatField(blank=True, null=True)),
                ('previous_sigma', models.FloatField(blank=True, null=True)),
                ('previous_points_float', models.FloatField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('last_known_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('tournaments', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=1000)),
                ('points_float', models.FloatField(default=1000)),
                ('sigma', models.FloatField(blank=True, null=True)),
                ('previous_sigma', models.FloatField(blank=True, null=True)),
                ('previous_points_float', models.FloatField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID discord')),
                ('PP_link', models.CharField(default='https://cdn.discordapp.com/embed/avatars/1.png', max_length=1000, verbose_name='lien de la PP')),
                ('badge_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('badge_tournament_winner', models.BooleanField(default=False, verbose_name='Tournament winner')),
                ('badge_old_first', models.BooleanField(default=False, verbose_name='ancien premier')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.teams', verbose_name='Équipe')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.IntegerField()),
                ('loser_score', models.IntegerField()),
                ('match_type', models.IntegerField(choices=[(1, 'Freeplay'), (2, 'Tournament'), (3, 'Inter Team')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_loser', to='ranking.member')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='ranking.member')),
            ],
        ),
    ]
