# Generated by Django 3.1.3 on 2020-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20201122_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='Nom du badge'),
            preserve_default=False,
        ),
    ]
