# Generated by Django 3.1.3 on 2020-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_badge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='svg',
            field=models.TextField(blank=True, verbose_name='modèle'),
        ),
    ]
