# Generated by Django 3.1.3 on 2020-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20201122_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='is_posseded',
        ),
        migrations.AddField(
            model_name='badge',
            name='tooltip',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
