# Generated by Django 3.1.3 on 2020-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_auto_20201122_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='did_tournament',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_badges',
            field=models.ManyToManyField(blank=True, to='ranking.Badge', verbose_name='Badges'),
        ),
    ]
