# Generated by Django 3.1.3 on 2020-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_auto_20201123_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='did_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
